### ISSUE TITLE
Docker compose setup fails

### ISSUE THREAD

**Issue by ThomasKoscheck** [hook0/hook0#15]
Hi, 
when running the docker compose command from the docs the setup fails as shown on the screen.
Docker command: `docker compose -f self-hosted/docker/docker-compose.yaml up --build --detach`

![image](https://github.com/hook0/hook0/assets/19782301/c0905a34-9697-4b92-a8b4-3598b57d2ca9)

When running without detach, the error is more detailed
![image](https://github.com/hook0/hook0/assets/19782301/84f01c31-1dca-4709-b93f-a535873b7e96)

I tried adding the named variables in the docker compose for the api service without luck

Kind regards,
Thomas

**Comment by dsferruzza** [comment]
Hi!
Thanks for your report!

This was indeed broken because we recently ditched Keycloak to allow for easier self hosting, and we are in the process of updating the documentation.
I just created a `iam-v2-docker` branch to fix this.

The Docker Compose file is now at the root of the repo, which means you can run it using the `docker compose up --build --detach` command.

Could you give it a try?
Depending on your feedback, I will merge and update the documentation!

**Comment by ThomasKoscheck** [comment]
Hi,
thanks for the quick fix!
The build now works, but creating the initial user did not work for me. 
(Creation via the provided curl is successful, but when trying to log in on the web i get a 401)

**Comment by dsferruzza** [comment]
Maybe you did not verify the user's email? You can connect to the mailpit instance to see sent emails (on http://localhost:8025 if I remember correctly). Or you can connect to the database and manually set the `verified_at` column of the `iam.user` table to `now()`.

**Comment by dsferruzza** [comment]
Wonderful! So you are up and running?

**Comment by ThomasKoscheck** [comment]
> Wonderful! So you are up and running?

yes, the service is up in running
i only tried the UI shortly but as mentioned on the dashboard, most parts are not usable yet (mostly 401/403 errors)

**Comment by dsferruzza** [comment]
This is not supposed to happen 🤔 Could you send me some details? Maybe try deleting your local storage on this domain and log in again?

**Comment by ThomasKoscheck** [comment]
Hey, 
I recorded a short walkthrough
Right before the screencast I deleted all local storage and did a fresh sign in.

Additionally I noticed, if you are doing a reload of the page, you have to start at the login page. Otherwise you will always get a `This localhost page cant be found` error

https://github.com/user-attachments/assets/41d17944-a5d2-44a5-9ab2-297be7e58271

Hope this helps

**Comment by dsferruzza** [comment]
Thanks a lot for your feedback!

I could reproduce and fix the 2 bugs!
I pushed the fixes in the same `iam-v2-docker` branch: could you pull it, rebuild/restart (`docker compose up --build --detach`) and let me know if you still have the issues?

**Comment by ThomasKoscheck** [comment]
Works perfectly!

**Comment by StreamlinedStartup** [comment]
Having same issues on the `iam-v2-docker` branch. 

- Create account via cURL. 
- Can't verify account via mailpit
![CleanShot 2024-08-17 at 00 39 01@2x](https://github.com/user-attachments/assets/b1405754-198e-4a44-a5f2-aa8798afdefe)
- Tried manually verifying by `manually set the verified_at column of the iam.user table to now().` but errored & doesn't exist. 

Here's my `docker-compose.yml`
```
name: hook0

volumes:
  postgres-data:
  mailpit-data:

services:
  postgres:
    image: postgres:15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hook0
    ports:
      - "5912:5432"
    networks:
      - hook0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $${POSTGRES_DB}"]
      timeout: 1s
      interval: 5s

  mailpit:
    image: axllent/mailpit:v1.19
    volumes:
      - ./mailpit-data:/data
    environment:
      - MP_DATABASE=/data/mailpit.db
      - POSTGRES_DB=hook0
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - hook0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider --user-agent 'docker-compose-healthcheck' http://localhost:8025/api/v1/info || exit 1"]
      timeout: 1s
      interval: 5s

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - IP=0.0.0.0
      - PORT=8081
      - CORS_ALLOWED_ORIGINS=http://192.168.68.73:8001
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hook0
      - SMTP_CONNECTION_URL=smtp://mailpit:1025
      - EMAIL_SENDER_ADDRESS=sender@hook0.local
      - APP_URL=http://192.168.68.73:8001
      - BISCUIT_PRIVATE_KEY=bbea79cd66926b219b3219a3186decb36136d774dd7c35a8239e512090fa8854  # DO NOT USE THIS KEY IN PRODUCTION
    ports:
      - "8081:8081"
    networks:
      - hook0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --user-agent 'docker-compose-healthcheck' http://localhost:$${PORT}/api/v1/swagger.json || exit 1"]
      timeout: 1s
      interval: 5s
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8001:80"
    networks:
      - hook0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --user-agent 'docker-compose-healthcheck' http://localhost || exit 1"]
      timeout: 1s
      interval: 5s
    depends_on:
      api:
        condition: service_healthy

  output-worker:
    build:
      context: .
      dockerfile: output-worker/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hook0
      - WORKER_NAME=default
      - DISABLE_TARGET_IP_CHECK=true
    networks:
      - hook0
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy

networks:
  hook0:
    driver: bridge
```
