### ISSUE TITLE
Activate application_secrets on self-hosted env

### ISSUE THREAD

**Issue by johanlelan-mgdis** [hook0/hook0#22]
Hi,

I am trying to setup hook0 via a self-hosted docker-compose. Everything works very well but after creating my organization and my app, I want to create an `application_secret` to use it in my code. As I've to figured it out, this feature is not configured yet. (see `Cargo.toml`)

```toml
[features]
default = ["reqwest-rustls-tls-webpki-roots", "migrate-users-from-keycloak", "application-secret-compatibility"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots", "hook0-client/reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots", "hook0-client/reqwest-rustls-tls-native-roots"]
migrate-users-from-keycloak = []
application-secret-compatibility = []
```

Do you have any documentation pointers to follow in order to enable this feature ?

Thanks in advance!

labels ~ Documentation
